apiVersion: k8s.cni.cncf.io/v1alpha1
kind: Multus
metadata:
  name: multus-sriov
spec:
  image: quay.io/krsacme/multus-cni-release
  release: v3.1
  delegates:
  - type: flannel
    name: flannel.1
  extensions:
    sriov:
      # TODO: Check if IPAM info could be added here?
      resources:
      - name: sriov_net1
        rootDevices:
        - 00:2:00
        type: netdevice
