apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multus-go-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multus-go-operator
  template:
    metadata:
      labels:
        name: multus-go-operator
        tier: control-plane
    spec:
      serviceAccountName: multus-go-operator
      priorityClassName: system-cluster-critical
      containers:
        - name: multus-go-operator
          # Replace this with the built image name
          image: dell-r640-001.dsal.lab.eng.rdu2.redhat.com:5000/krsacme/multus-go-operator 
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - multus-go-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multus-go-operator"
