apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-go-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multus-go-operator
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: multus-go-operator
        tier: control-plane
    spec:
      serviceAccountName: multus-go-operator
      containers:
        - name: multus-go-operator
          image: quay.io/krsacme/multus-go-operator 
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - multus-go-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multus-go-operator"
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: multus-go-operator
      serviceAccountName: multus-go-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists

